apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
type: Opaque
stringData:
  POSTGRES_DB: "oficina"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SECURITY_JWT_SECRET: "jwt-k8s-local-secret-123456789012345678901234567890"
